services:
  nginx:
    build:
      context: ./requirements/nginx
    image: nginx:hrazafia
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    depends_on:
      mariadb:
        condition: service_healthy
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/hrazafia.42.fr
      - ssl_data:/etc/ssl/hrazafia.42.fr
      - nginx_logs:/var/log/nginx
    networks:
      - frontend_network

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress:hrazafia
    container_name: wordpress
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_passwd
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_passwd
    volumes:
      - wordpress_data:/var/www/hrazafia.42.fr
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - frontend_network
      - backend_network
    secrets:
      - db_passwd
      - db_root_passwd

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb:hrazafia
    container_name: mariadb
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/db_passwd
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_passwd
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend_network
    secrets:
      - db_passwd
      - db_root_passwd

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/hrazafia/data/db
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/hrazafia/data/www/hrazafia.42.fr
      o: bind
  ssl_data:
    driver: local
    driver_opts:
      type: none
      device: /home/hrazafia/data/ssl/hrazafia.42.fr
      o: bind
  nginx_logs:
    driver: local
    driver_opts:
      type: none
      device: /home/hrazafia/data/logs
      o: bind

secrets:
  db_passwd:
    file: ../secrets/db_passwd.txt
  db_root_passwd:
    file: ../secrets/db_root_passwd.txt
  admin_passwd:
    file: ../secrets/admin_passwd.txt
  user_passwd:
    file: ../secrets/user_passwd.txt


networks:
  frontend_network:
    driver: bridge
  backend_network:
    driver: bridge
